### ISSUE TITLE
Update prost dependency to get build fix for Apple M1

### ISSUE THREAD

**Issue by nlfiedler** [google-apis-rs/google-cloud-rs#38]
The most recent release of prost (0.7) has a fix for building on Apple M1-based systems. The latest google-cloud-rs is still using version 0.6 which fails to build on Apple Silicon because prost was lacking a prebuilt `protoc` binary.

**Comment by Hirevo** [comment]
Hello !

We indeed had rather old dependencies for a long time and that is my bad for not keeping up, sorry about that.  
We now did a complete dependency upgrade and `v0.2.0` has been released with these upgrades (which includes `prost v0.7.0`).  

I am closing this issue, hoping that it fixes the issue.  
Don't hesitate to come back if it didn't and we can try to look further into it.

**Comment by nlfiedler** [comment]
Fantastic, thank you. Thanks for also updating tokio to 1.0. I verified that everything builds on `stable-aarch64-apple-darwin` without the need for installing the `protobuf` Homebrew keg.
